-----------------------------------------------
-------------------MEMBER-----------------------
-----------------------------------------------

-- 1-1. MEMBER 테이블 추가
CREATE TABLE "MEMBER" (
	"MEMBER_NO"					NUMBER 					NOT NULL,
	"MEMBER_EMAIL"			NVARCHAR2(50)		NOT NULL,
	"MEMBER_PW"					NVARCHAR2(100)		NOT NULL,
	"MEMBER_NICKNAME"		NVARCHAR2(10)		NOT NULL,
	"PROFILE_IMG"				VARCHAR2(300)		NULL,
	"ENROLL_DATE"				DATE						DEFAULT SYSDATE NOT NULL,
	"MEMBER_DEL_FL"			CHAR(1)					DEFAULT 'N' NOT NULL, 
	"MEMBER_BIRTH"			VARCHAR(8)			NOT NULL,
	"MEMBER_TEL"				VARCHAR(13)			NOT NULL,
	"MEMBER_ADDRESS"		NVARCHAR2(300)	NULL,
	"AUTHORITY"					NUMBER					DEFAULT 1 NOT NULL,
	"MEMBER_BG"					NUMBER					DEFAULT 1 NOT NULL,
	"MEMBER_SCHOOL" 		NVARCHAR2(40) NOT NULL
);

-- Test ( dasol )
INSERT INTO "MEMBER" VALUES(SEQ_MEMBER_NO.NEXTVAL, 'dasol@gmail.com',
'dks123', 'dasol', NULL, SYSDATE, 'N', '20001213',

'010-1234-1234', '서울시 종로구', 1, 1, 'samsung');

UPDATE "MEMBER"
SET MEMBER_ADDRESS = '03189^^^서울 종로구 우정국로2길 21^^^3층, 302 강의실'
WHERE MEMBER_NO = 8;

SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_PW, MEMBER_NICKNAME,
		PROFILE_IMG, TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" SS"초"') ENROLL_DATE,
		MEMBER_DEL_FL, MEMBER_BIRTH, MEMBER_TEL, MEMBER_ADDRESS, 
		AUTHORITY, MEMBER_BG, MEMBER_SCHOOL, QUOTES_CONTENT, QUOTES_FONT_SIZE, QUOTES_FONT_FAMILY
		FROM "MEMBER"
		WHERE MEMBER_EMAIL = 'ads11121316@gmail.com'
		AND MEMBER_DEL_FL = 'N';

COMMIT;

UPDATE "MEMBER"
SET MEMBER_PW = '$2a$10$ccb9xXtN0jZRzNm39cMjtOx6dKCpdZxm1je2RHzPu/gdaUY4Ukd5S'
WHERE MEMBER_NO = 8;

-- MEMBER SELECT
SELECT * FROM "MEMBER";


UPDATE "MEMBER"
SET MEMBER_DEL_FL = 'N'
WHERE MEMBER_NO = 8;

DELETE FROM "MEMBER"
WHERE MEMBER_NO = 8;

-- 1. 해당 회원이 쓴 게시글들 먼저 삭제
DELETE FROM "BOARD" 
WHERE MEMBER_NO = 8;

SELECT MEMBER_NO
FROM "BOARD"
WHERE MEMBER_NO = 8;

DELETE FROM "COMMENT"
WHERE MEMBER_NO = 8;

SELECT MEMBER_NO
FROM "COMMENT"
WHERE MEMBER_NO = 8;

SELECT PARENT_COMMENT_NO
FROM "COMMENT"
WHERE MEMBER_NO = 8;

DELETE FROM "BOARD_IMG" 
WHERE MEMBER_NO = 23;

-- 2. 이제 회원 삭제 (방해물이 없으니 성공!)
DELETE FROM "MEMBER" WHERE MEMBER_NO = 23;

COMMIT;

COMMIT;

SELECT * FROM EMAIL_AUTH_KEY;

DELETE FROM "EMAIL_AUTH_KEY"
WHERE KEY_NO = 5;

SELECT MEMBER_PW
		FROM MEMBER
		WHERE MEMBER_NO = 8;

SELECT * FROM EMAIL_AUTH_KEY;

-- 학교 컬럼 누락되어 아래 ALTER 구문으로 추가함
ALTER TABLE "MEMBER" ADD ("MEMBER_SCHOOL" NVARCHAR2(20) NOT NULL);

-- SCHOOL 컬럼 크기 수정
ALTER TABLE "MEMBER" MODIFY ("MEMBER_SCHOOL" NVARCHAR2(40));

COMMIT; -- 수행

-- 닉네임 중복 검사 test
SELECT COUNT(*)
  	FROM "MEMBER"
  	WHERE MEMBER_DEL_FL = 'N'
  	AND MEMBER_NICKNAME = 'seongjong';

-- 내 정보 수정
UPDATE "MEMBER"
SET MEMBER_NICKNAME = 'test'
AND MEMBER_TEL = '010098765432'
AND MEMBER_ADDRESS = '광명 2동'
WHERE = 13;

-- 회원 탈퇴 여부
UPDATE "MEMBER"
SET MEMBER_DEL_FL = 'N'
WHERE MEMBER_NO = 23;



	/* 
	 수정 사항
	 1) MEMBER_ADDRESS : 기본값 NULL 로 변경 
	    - 사유 : 회원가입 시 필수입력 X
	 
	 2) MEMBER_BG : NUMBER 타입으로 변경
	    - 사유 : 현 단계에서 마이페이지 제공 컬러테마 총 8개
	  					 따라서 NUMBER 형으로 지정하여 1~8까지 각각 상응하는 컬러테마 지정하는 게 가능 및
	  					 추후 컬러 추가하기에도 용이하며 NVARCHAR로 할 시 오타 발생 상황 방지 용이 
	
   3) 학교 컬럼 추가 					 */

	 
	 
ALTER TABLE "MEMBER" MODIFY ("MEMBER_BG" NOT NULL);
ALTER TABLE "MEMBER" MODIFY "MEMBER_BG" NUMBER;
ALTER TABLE "MEMBER" MODIFY "MEMBER_BG" DEFAULT 1;

COMMIT;

-- 1-2. 각 컬럼별 COMMENT 추가
COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호(PK)';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 별명(활동명)';
COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '회원 프로필 이미지';
COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '탈퇴여부';
COMMENT ON COLUMN "MEMBER"."MEMBER_BIRTH" IS '생년월일';
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '전화번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '주소';
COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '권한(1=회원 2=관리자)';
COMMENT ON COLUMN "MEMBER"."MEMBER_BG" IS '회원 테마색(1~8)';


-- 2. MEMBER_NO 컬럼 PK 제약조건 추가
ALTER TABLE "MEMBER" 
ADD CONSTRAINT "PK_MEMBER" 
PRIMARY KEY ("MEMBER_NO");

-- 3-1. MEMBER_NO 에 들어갈 SEQUENCE 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

-- 3-2. 최초 번호 생성
SELECT SEQ_MEMBER_NO.NEXTVAL FROM DUAL; 

-- 3-3. 현재 번호 확인
SELECT SEQ_MEMBER_NO.CURRVAL FROM DUAL; 

-- 3-4. 증감 변경 
ALTER SEQUENCE SEQ_MEMBER_NO INCREMENT BY 1;

SELECT * FROM "MEMBER";

DELETE FROM "MEMBER"
WHERE MEMBER_EMAIL = 'ads1213@gmail.com';

DROP SEQUENCE SEQ_MEMBER_NO;
DROP TABLE "MEMBER" CASCADE CONSTRAINTS;

COMMIT;

-----------------------------------------------
-------------------AUTH_KEY-----------------------
-----------------------------------------------
CREATE TABLE "EMAIL_AUTH_KEY" (
	"KEY_NO" NUMBER PRIMARY KEY,	
	"EMAIL" NVARCHAR2(50) NOT NULL,	
	"AUTH_KEY" CHAR(6) NOT NULL,	
	"CREATE_TIME" DATE DEFAULT SYSDATE NOT NULL	
); -- 수행

COMMENT ON COLUMN "EMAIL_AUTH_KEY"."KEY_NO"      IS '인증키 구분 번호(시퀀스)';
COMMENT ON COLUMN "EMAIL_AUTH_KEY"."EMAIL"       IS '인증 이메일';
COMMENT ON COLUMN "EMAIL_AUTH_KEY"."AUTH_KEY"    IS '인증 번호';
COMMENT ON COLUMN "EMAIL_AUTH_KEY"."CREATE_TIME" IS '인증 번호 생성 시간';
-- 수행

CREATE SEQUENCE SEQ_KEY_NO NOCACHE; -- 인증키 구분 번호 시퀀스

COMMIT; -- 수행

SELECT * FROM EMAIL_AUTH_KEY;

-- 이메일 + 인증번호 일치하는 행 조회
SELECT COUNT(*)
		FROM EMAIL_AUTH_KEY
		WHERE AUTH_KEY = '609905';

UPDATE EMAIL_AUTH_KEY
		SET EMAIL_AUTH_KEY = '123456'
		CREATE_TIME = 'SYSDATE'
		WHERE EMAIL = 'dasol619059@gmail.com';

SELECT COUNT(*)
		FROM EMAIL_AUTH_KEY
		WHERE AUTH_KEY = '415d15';


-----------------------------------------------
-------------------CALENDER-----------------------
-----------------------------------------------

CREATE TABLE "CALENDER" (
	"CALENDER_ID" NUMBER NOT NULL, -- PK
	"START_DATE" DATE NOT NULL,
	"END_DATE"	DATE NOT NULL,
	"CALENDER_CONTENT" NVARCHAR2(100) NOT NULL, -- 특정 일자의 캘린더 내용
	"MEMBER_NO" NUMBER NOT NULL, -- FK
	CONSTRAINT "PK_CALENDER" PRIMARY KEY ("CALENDER_ID"),
	CONSTRAINT "FK_MEMBER_NO_TO_CALENDER" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
	);

SELECT * FROM CALENDER;

CREATE SEQUENCE SEQ_CALENDER_ID;
ALTER SEQUENCE SEQ_CALENDER_ID INCREMENT BY 1;

INSERT INTO "CALENDER" VALUES(
	SEQ_CALENDER_ID.NEXTVAL,
	SYSDATE + 12,
	SYSDATE + 44,
	'테스트444',
	10
);

COMMIT;


-----------------------------------------------
-------------------TIME_TABLE-----------------------
-----------------------------------------------

CREATE TABLE "TIMETABLE" (
	"TIMETABLE_ID"	NUMBER	NOT NULL,	
	"DAY_OF_WEEK"		NUMBER	NOT NULL,
	"SEMESTER"			NVARCHAR2(10) NOT NULL,
	"SUBJECT"				NVARCHAR2(10)	NULL,
	"MEMBER_NO"			NUMBER	NOT NULL
);

/* 수정사항
 1) END_DATE 및 START_DATE 삭제
  - 사유 : 굳이 필요하지 않은 데이터인 듯하여 삭제하였습니다.
 
 2) SEMESTER(학기) 추가
  - 사유 : 1)과 관련하여, '2025년도 1학기', '2026년도 2학기' 등처럼 학기만 나타내주는 컬럼이 필요하여 추가
 
 3) DAY_OF_WEEK 을 NUMBER 타입으로 변경
  - 사유 : 일주일 단위기간을 숫자로 나타내어 오타로 인한 오류 방지 용이
  
 4) SUBJECT 를 NULL 허용으로 변경
  - 사유 : 반드시 7교시가 아니라 4교시, 5교시 등도 있을 수 있기 때문에 NULL 허용
*/

COMMENT ON COLUMN "TIMETABLE"."TIMETABLE_ID" IS '시간표번호(PK)';
COMMENT ON COLUMN "TIMETABLE"."DAY_OF_WEEK" IS '요일';
COMMENT ON COLUMN "TIMETABLE"."SEMESTER" IS '학기';
COMMENT ON COLUMN "TIMETABLE"."SUBJECT" IS '과목';
COMMENT ON COLUMN "TIMETABLE"."MEMBER_NO" IS '회원번호(FK)';

ALTER TABLE "TIMETABLE"
ADD CONSTRAINT "PK_TIMETABLE" 
PRIMARY KEY ("TIMETABLE_ID");

SELECT * FROM "TIMETABLE";

-- TIMETABLE_ID 에 들어갈 SEQUENCE 생성
CREATE SEQUENCE SEQ_TIMETABLE_ID NOCACHE;

-- 최초 번호 생성
SELECT SEQ_TIMETABLE_ID.NEXTVAL FROM DUAL; 

-- 현재 번호 확인
SELECT SEQ_TIMETABLE_ID.CURRVAL FROM DUAL; 

-- 증감 변경 
ALTER SEQUENCE SEQ_TIMETABLE_ID INCREMENT BY 1;

COMMIT;

DROP TABLE "TIMETABLE" CASCADE CONSTRAINTS;





-----------------------------------------------
-------------------BOARD_TYPE----------------------
-----------------------------------------------

CREATE TABLE "BOARD_TYPE" (
	"BOARD_TYPE_NO"		NUMBER			NOT NULL,
	"BOARD_TYPE_NAME"	NVARCHAR2(20)	NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_TYPE_NO" IS '게시판 종류코드반 번호(PK)';
COMMENT ON COLUMN "BOARD_TYPE"."BOARD_TYPE_NAME" IS '게시판 이름';

DROP SEQUENCE SEQ_BOARD_CODE;

CREATE SEQUENCE SEQ_BOARD_CODE
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 글자수 제한 초과로 인해 NVARCHAR2(20)으로 컬럼 타입 변경
ALTER TABLE "BOARD_TYPE" MODIFY "BOARD_TYPE_NAME" NVARCHAR2(20);

INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '자유 게시판');
INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '질문 게시판');
INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '급식표 게시판');
INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '입시정보 게시판');
INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '문제풀이 게시판');
INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '공지사항');
INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '마이페이지 게시판'); -- 확인 후 수행할것

COMMIT;

SELECT * FROM BOARD_TYPE;

ALTER TABLE "BOARD_TYPE" 
ADD CONSTRAINT "PK_BOARD_TYPE" 
PRIMARY KEY ("BOARD_TYPE_NO");





-----------------------------------------------
-------------------BOARD-----------------------
-----------------------------------------------
--****************** "BOARD_NO" 이 아니라 "BOARD_ID" 임에 주의

CREATE TABLE "BOARD" (
	"BOARD_ID"	NUMBER	NOT NULL, --PK
	"BOARD_TITLE"	NVARCHAR2(20)	NOT NULL,
	"BOARD_CONTENT"	NVARCHAR2(2000)	NOT NULL, -- 게시글 내용 2000자
	"BOARD_VIEW_COUNT"	NUMBER	DEFAULT 0 NOT NULL,
	"BOARD_IS_DELETED"	CHAR(1)	DEFAULT 'N' NOT NULL,
	"BOARD_CREATE_DATE"	DATE	DEFAULT SYSDATE NOT NULL,
	"BOARD_UPDATE_DATE"	DATE	DEFAULT SYSDATE NOT NULL, -- 수정일자 DEFAULT 값 SYSDATE 로 추가, NOT NULL 로 변경
	"BOARD_TYPE_NO"	NUMBER	NOT NULL, -- FK
	"MEMBER_NO"	NUMBER	NOT NULL -- FK
);

-- PK 지정
ALTER TABLE "BOARD" 
ADD CONSTRAINT "PK_BOARD" 
PRIMARY KEY ("BOARD_ID");

-- 시퀀스 생성
CREATE SEQUENCE "SEQ_BOARD_ID"
START WITH 1
INCREMENT BY 1
NOCACHE;

-- FK 지정
ALTER TABLE "BOARD" 
ADD CONSTRAINT "FK_BOARD_TYPE TO BOARD" 
FOREIGN KEY ("BOARD_TYPE_NO")
REFERENCES "BOARD_TYPE" ("BOARD_TYPE_NO"); 

ALTER TABLE "BOARD" 
ADD CONSTRAINT "FK_MEMBER_NO TO BOARD" 
FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO"); 

SELECT * FROM "BOARD";

COMMIT;





-----------------------------------------------
-------------------COMMENT-----------------------
-----------------------------------------------

CREATE TABLE "COMMENT" (
	"COMMENT_NO"			NUMBER	NOT NULL, --PK
	"COMMENT_CONTENT" NVARCHAR2(1000)	NOT NULL, -- 댓글 내용 1000자
	"COMMENT_WRITE_DATE"	DATE	DEFAULT SYSDATE NOT NULL, -- DEFAULT SYSDATE 추가
	"COMMENT_DEL_FL"		CHAR(1)	DEFAULT 'N' NOT NULL,
	"BOARD_ID"	NUMBER	NOT NULL, -- FK
	"MEMBER_NO"	NUMBER	NOT NULL,	-- FK
	"PARENT_COMMENT_NO"	NUMBER	NOT NULL	-- FK
);

ALTER TABLE "COMMENT" RENAME COLUMN "BOARD_NO" TO "BOARD_ID";

-- PK 지정
ALTER TABLE "COMMENT" 
ADD CONSTRAINT "PK_COMMENT" 
PRIMARY KEY ("COMMENT_NO");

-- 시퀀스 생성
CREATE SEQUENCE "SEQ_COMMENT_NO"
START WITH 1
INCREMENT BY 1
NOCACHE;

-- FK 지정
ALTER TABLE "COMMENT" 
ADD CONSTRAINT "FK_BOARD_ID TO COMMENT" 
FOREIGN KEY ("BOARD_ID")
REFERENCES "BOARD" ("BOARD_ID"); 

ALTER TABLE "COMMENT"
ADD CONSTRAINT "FK_MEMBER_NO TO COMMENT"
FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");

ALTER TABLE "COMMENT"
ADD CONSTRAINT "FK_PARENT_COMMENT_NO TO COMMENT"
FOREIGN KEY ("COMMENT_NO")
REFERENCES "COMMENT" ("COMMENT_NO");

SELECT * FROM "COMMENT";




-----------------------------------------------
------------------BOARD_IMG-----------------------
-----------------------------------------------

CREATE TABLE "BOARD_IMG" (
	"IMG_NO"	NUMBER	NOT NULL,	-- '이미지 번호(PK)',
	"IMG_PATH"	VARCHAR(200)	NOT NULL,	-- '이미지 요청 경로',
	"IMG_ORIGINAL_NAME"	NVARCHAR2(50)	NOT NULL,	-- '이미지 원본명',
	"IMG_RENAME"	NVARCHAR2(50)	NOT NULL,
	"IMG_ORDER"	NUMBER	NULL,
	"BOARD_ID"	NUMBER	NOT NULL -- FK
);

-- PK 생성
ALTER TABLE "BOARD_IMG" 
ADD CONSTRAINT "PK_BOARD_IMG" 
PRIMARY KEY ("IMG_NO");

-- 시퀀스 생성
CREATE SEQUENCE "SEQ_IMG_NO"
START WITH 1
INCREMENT BY 1
NOCACHE;

-- FK 지정
ALTER TABLE "BOARD_IMG"
ADD CONSTRAINT "FK_BOARD_ID TO BOARD_IMG"
FOREIGN KEY ("BOARD_ID")
REFERENCES "BOARD" ("BOARD_ID");






-----------------------------------------------
------------------BOARD_LIKE-------------------
-----------------------------------------------

CREATE TABLE "BOARD_LIKE" (
	"MEMBER_NO"	NUMBER	NOT NULL,	-- '회원번호(PFK)'
	"BOARD_ID"	NUMBER	NOT NULL	-- '게시글번호(PK)'
);

-- PK 지정

ALTER TABLE "BOARD_LIKE" 
ADD CONSTRAINT "PK_BOARD_LIKE" 
PRIMARY KEY ("MEMBER_NO", "BOARD_ID");

ALTER TABLE "BOARD_LIKE"
ADD CONSTRAINT "FK_MEMBER_NO TO BOARD_LIKE"
FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");

SELECT * FROM "BOARD_LIKE";




-----------------------------------------------
------------------UPLOAD_FILE-------------------
-----------------------------------------------

CREATE TABLE "UPLOAD_FILE" (
	"UPLOADFILE_NO"	NUMBER	NOT NULL,	-- '파일 번호'
	"UPLOADFILE_ORIGIN"	VARCHAR2(150)	NOT NULL,	--'원본 파일명'
	"UPLOADFILE_PATH"	VARCHAR2(1000)	NOT NULL,	--'파일 경로'
	"UPLOADFILE_STRG"	VARCHAR2(150)	NOT NULL,	-- '저장 파일명'
	"UPLOADFILE_SIZE"	NUMBER	NOT NULL,	-- '파일 크기'
	"UPLOADFILE_DATE"	DATE	DEFAULT SYSDATE NOT NULL, --파일 날짜	
	"BOARD_ID"	NUMBER	NOT NULL	-- '게시글번호(FK)'
);

-- PK 생성
ALTER TABLE "UPLOAD_FILE" 
ADD CONSTRAINT "PK_UPLOAD_FILE" 
PRIMARY KEY ("UPLOADFILE_NO");

-- 시퀀스 생성
CREATE SEQUENCE "SEQ_UPLOADFILE_NO"
START WITH 1
INCREMENT BY 1
NOCACHE;

-- FK 지정
ALTER TABLE "UPLOAD_FILE"
ADD CONSTRAINT "FK_BOARD_ID TO UPLOAD_FILE"
FOREIGN KEY ("BOARD_ID")
REFERENCES "BOARD" ("BOARD_ID");

COMMIT;

SELECT * FROM UPLOAD_FILE;

-----------------------------------------------
---------------PROFILE_UPLOAD_FILE-------------
-----------------------------------------------
-- dasol
CREATE TABLE "PROFILE_UPLOAD_FILE" (
	"FILE_NO"	NUMBER	NOT NULL,	-- '파일 번호(PK)'
	"FILE_PATH"	VARCHAR2(500)	NOT NULL,	--'파일 요청 경로'
	"FILE_ORIGINAL_NAME"	VARCHAR2(300)	NOT NULL,	--'파일 원본명'
	"FILE_RENAME"	VARCHAR2(100)	NOT NULL,	-- '파일 변경명'
	"FILE_UPLOAD_DATE"	DATE	NOT NULL,	-- '업로드 날짜'
	"MEMBER_NO"	NUMBER	NOT NULL	-- '업로드한 회원 번호(FK)'
);

CREATE TABLE "PROFILE_UPLOAD_FILE" (
    "FILE_NO" NUMBER PRIMARY KEY,
    "FILE_PATH" VARCHAR2(500) NOT NULL,
    "FILE_ORIGINAL_NAME"	VARCHAR2(300)	NOT NULL,	--'파일 원본명'
	"FILE_RENAME"	VARCHAR2(100)	NOT NULL,	-- '파일 변경명'
	"FILE_UPLOAD_DATE"	DATE	NOT NULL,	-- '업로드 날짜'
    "MEMBER_NO" NUMBER NOT NULL, -- FK로 연결할 컬럼
    -- 테이블 생성할 때 바로 제약조건 걸기!
    CONSTRAINT "FK_MEMBER_TO_PROFILE" 
    FOREIGN KEY ("MEMBER_NO") 
    REFERENCES "MEMBER" ("MEMBER_NO")
); -- 수행함

COMMENT ON COLUMN "PROFILE_UPLOAD_FILE"."FILE_NO" IS '파일 번호(PK)';
COMMENT ON COLUMN "PROFILE_UPLOAD_FILE"."FILE_PATH" IS '파일 요청 경로';
COMMENT ON COLUMN "PROFILE_UPLOAD_FILE"."FILE_ORIGINAL_NAME" IS '파일 원본명';
COMMENT ON COLUMN "PROFILE_UPLOAD_FILE"."FILE_RENAME" IS '파일 변경명';
COMMENT ON COLUMN "PROFILE_UPLOAD_FILE"."FILE_UPLOAD_DATE" IS '업로드 날짜';
COMMENT ON COLUMN "PROFILE_UPLOAD_FILE"."MEMBER_NO" IS '업로드한 회원 번호';

SELECT * FROM "PROFILE_UPLOAD_FILE";

-- 시퀀스 SEQ_FILE_NO 생성
CREATE SEQUENCE SEQ_FILE_NO NOCACHE;

ALTER TABLE "PROFILE_UPLOAD_FILE" ADD CONSTRAINT 
	"PK_PROFILE_UPLOAD_FILE" PRIMARY KEY (
	"FILE_NO"
); -- 수행함

COMMIT;

DROP TABLE "PROFILE_UPLOAD_FILE";
-- 제약 조건(FK)을 포함한 CREATE 문 실행

ALTER TABLE "PROFILE_UPLOAD_FILE" 
ADD CONSTRAINT "FK_MEMBER_TO_PROFILE_UPLOAD_FILE_1" 
FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");

-- !!!!!! 아래부터 주석처리함.
-- !!!!!! 필요한 거 잘라내서 추가해주세요

/* 



CREATE TABLE `TODO` (
	`TODO_NO`	NUMBER	NOT NULL	COMMENT '할일 번호(PK)',
	`TODO_TITLE`	VARCHAR(200)	NOT NULL	COMMENT '할일 제목',
	`TODO_CONTENT`	VARCHAR2(4000)	NOT NULL	COMMENT '할일 내용',
	`TODO_CHECK`	CHAR(1)	NULL	DEFAULT N	COMMENT '할일 체크',
	`TODO_DATE`	DATE	NOT NULL	COMMENT '할일 날짜',
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(FK)'
);


CREATE TABLE `DIARY` (
	`DIARY_NO`	NUMBER	NOT NULL	COMMENT '일기장 번호(PK)',
	`DIARY_DATE`	DATE	NOT NULL	COMMENT '일기장 날짜',
	`DIARY_TITLE`	NVARCHAR2(50)	NOT NULL	COMMENT '일기장 제목',
	`DIARY_CONTENT`	NVARCHAR2(2000)	NOT NULL	COMMENT '일기장 내용',
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(FK)'
);

CREATE TABLE `WRONG_NOTE` (
	`WRONG_NOTE_NO`	NUMBER	NOT NULL	COMMENT '할일 번호(PK)',
	`WRONG_NOTE_TITLE`	VARCHAR(200)	NOT NULL	COMMENT '오답노트 제목',
	`WRONG_NOTE_CONTENT`	VARCHAR2(4000)	NOT NULL	COMMENT '오답노트 내용',
	`WRONG_NOTE_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '오답노트 작성일',
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(FK)'
);

CREATE TABLE `INQUIRY` (
	`INQUIRY_NO`	NUMBER	NOT NULL	COMMENT '문의 번호',
	`INQUIRY_TITLE`	NVARCHAR2(50)	NOT NULL	COMMENT '문의사항 분류',
	`INQUIRY_CONTENT`	NVARCHAR2(1000)	NOT NULL	COMMENT '세부문의사항',
	`INQUIRY_COMPLETE`	CHAR(1)	NOT NULL	DEFAULT N	COMMENT '조치완료여부(N/Y)',
	`INQUIRY_DATE`	DATE	NOT NULL	COMMENT '문의한 날짜',
	`INQUIRY_COMPLETE_DATE`	DATE	NOT NULL	COMMENT '답변한 날짜',
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(PK)'
);


CREATE TABLE `CHAT_MESSAGE` (
	`MSG_NO`	NUMBER	NOT NULL	COMMENT '메시지 고유 번호(PK)',
	`MESSAGE`	VARCHAR2(4000)	NOT NULL	COMMENT '메시지 내용',
	`READ_YN`	CHAR(1)	NOT NULL	COMMENT '읽음 여부("Y" 또는 "N")',
	`SEND_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '보낸 시간(기본값: 현재시간)',
	`ROOM_NO2`	NUMBER	NOT NULL	COMMENT '채팅방 번호(PK)',
	`SENDER_NO`	NUMBER	NOT NULL	COMMENT '메시지보낸회원번호(PK)'
);


CREATE TABLE `ATTENDANCE` (
	`ATTENDANCE_DATE`	DATE	NOT NULL	COMMENT '출석시간(PK)',
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(PFK)',
	`ATTENDANCE_NO`	NUMBER	NOT NULL	COMMENT '출석고유번호(UNIQUE)'
);

CREATE TABLE `AUTH_KEY_EMAIL` (
	`EMAIL_KEY_NO`	NUMBER	NOT NULL	COMMENT '이메일 인증 키 번호(PK)',
	`EMAIL`	NVARCHAR2(50)	NOT NULL	COMMENT '이메일 주소',
	`AUTH_KEY`	CHAR(6)	NOT NULL	COMMENT '이메일 인증 번호',
	`AUTH_CREATE_TIME`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '이메일 인증번호 생성 시간'
);

CREATE TABLE `D_DAY` (
	`D_DAY_NO`	NUMBER	NOT NULL	COMMENT 'D_DAY PK',
	`D_DAY_TITLE`	NVARCHAR2(20)	NULL,
	`D_DAY_MENT`	NVARCHAR2(100)	NULL,
	`D_DAY`	DATE	NULL,
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(FK)'
);

CREATE TABLE `POINT_LOG` (
	`POINT_LOG_ID`	NUMBER	NOT NULL	COMMENT '포인트번호(PK)',
	`POINT`	NUMBER	NOT NULL,
	`POINT_REASON`	NVARCHAR(255)	NOT NULL,
	`POINT_CREATE_AT`	DATE	NOT NULL,
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(PK)',
	`ATTENDANCE_NO`	NUMBER	NOT NULL	COMMENT '출석고유번호(UNIQUE)'
);



CREATE TABLE `CHAT_ROOM` (
	`ROOM_NO`	NUMBER	NOT NULL	COMMENT '채팅방 번호(PK)',
	`CREATE_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '생성일',
	`PARTICIPANT`	NUMBER	NOT NULL	COMMENT '참여자(FK)',
	`OPEN_MEMBER`	NUMBER	NOT NULL	COMMENT '개설자(FK)'
);





ALTER TABLE `TODO` ADD CONSTRAINT `PK_TODO` PRIMARY KEY (
	`TODO_NO`
);



ALTER TABLE `DIARY` ADD CONSTRAINT `PK_DIARY` PRIMARY KEY (
	`DIARY_NO`
);

ALTER TABLE `WRONG_NOTE` ADD CONSTRAINT `PK_WRONG_NOTE` PRIMARY KEY (
	`WRONG_NOTE_NO`
);

ALTER TABLE `INQUIRY` ADD CONSTRAINT `PK_INQUIRY` PRIMARY KEY (
	`INQUIRY_NO`
);

ALTER TABLE `CHAT_MESSAGE` ADD CONSTRAINT `PK_CHAT_MESSAGE` PRIMARY KEY (
	`MSG_NO`
);

ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `PK_ATTENDANCE` PRIMARY KEY (
	`ATTENDANCE_DATE`,
	`MEMBER_NO`
);

ALTER TABLE `AUTH_KEY_EMAIL` ADD CONSTRAINT `PK_AUTH_KEY_EMAIL` PRIMARY KEY (
	`EMAIL_KEY_NO`
);

ALTER TABLE `D_DAY` ADD CONSTRAINT `PK_D_DAY` PRIMARY KEY (
	`D_DAY_NO`
);

ALTER TABLE `POINT_LOG` ADD CONSTRAINT `PK_POINT_LOG` PRIMARY KEY (
	`POINT_LOG_ID`
);


ALTER TABLE `CHAT_ROOM` ADD CONSTRAINT `PK_CHAT_ROOM` PRIMARY KEY (
	`ROOM_NO`
);


ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `FK_MEMBER_TO_ATTENDANCE_1` FOREIGN KEY (
	`MEMBER_NO`
)

*/