-----------------------------------------------
-------------------MEMBER-----------------------
-----------------------------------------------

-- 1-1. MEMBER 테이블 추가
CREATE TABLE "MEMBER" (
	"MEMBER_NO"					NUMBER 					NOT NULL,
	"MEMBER_EMAIL"			NVARCHAR2(50)		NOT NULL,
	"MEMBER_PW"					NVARCHAR2(100)		NOT NULL,
	"MEMBER_NICKNAME"		NVARCHAR2(10)		NOT NULL,
	"PROFILE_IMG"				VARCHAR2(300)		NULL,
	"ENROLL_DATE"				DATE						DEFAULT SYSDATE NOT NULL,
	"MEMBER_DEL_FL"			CHAR(1)					DEFAULT 'N' NOT NULL, 
	"MEMBER_BIRTH"			VARCHAR(8)			NOT NULL,
	"MEMBER_TEL"				VARCHAR(13)			NOT NULL,
	"MEMBER_ADDRESS"		NVARCHAR2(300)	NULL,
	"AUTHORITY"					NUMBER					DEFAULT 1 NOT NULL,
	"MEMBER_BG"					NUMBER					DEFAULT 1 NOT NULL,
	"MEMBER_SCHOOL" 		NVARCHAR2(20) NOT NULL
);

-- 학교 컬럼 누락되어 아래 ALTER 구문으로 추가함
ALTER TABLE "MEMBER" ADD ("MEMBER_SCHOOL" NVARCHAR2(20) NOT NULL);

	/* 
	 수정 사항
	 1) MEMBER_ADDRESS : 기본값 NULL 로 변경 
	    - 사유 : 회원가입 시 필수입력 X
	 
	 2) MEMBER_BG : NUMBER 타입으로 변경
	    - 사유 : 현 단계에서 마이페이지 제공 컬러테마 총 8개
	  					 따라서 NUMBER 형으로 지정하여 1~8까지 각각 상응하는 컬러테마 지정하는 게 가능 및
	  					 추후 컬러 추가하기에도 용이하며 NVARCHAR로 할 시 오타 발생 상황 방지 용이 
	
   3) 학교 컬럼 추가 					 */

INSERT INTO "MEMBER" VALUES(
	SEQ_MEMBER_NO.NEXTVAL,
	'chulgu@test.co.kr',
	'1111',
	'철구님 테스트',
	NULL,
	DEFAULT,
	DEFAULT,
	'20091010',
	'010-0100-0101',
	NULL,
	DEFAULT,
	DEFAULT,
	'고등학교'
);	 

	 
ALTER TABLE "MEMBER" MODIFY ("MEMBER_BG" NOT NULL);
ALTER TABLE "MEMBER" MODIFY "MEMBER_BG" NUMBER;
ALTER TABLE "MEMBER" MODIFY "MEMBER_BG" DEFAULT 1;

COMMIT;

-- 1-2. 각 컬럼별 COMMENT 추가
COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호(PK)';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 별명(활동명)';
COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '회원 프로필 이미지';
COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '탈퇴여부';
COMMENT ON COLUMN "MEMBER"."MEMBER_BIRTH" IS '생년월일';
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '전화번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '주소';
COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '권한(1=회원 2=관리자)';
COMMENT ON COLUMN "MEMBER"."MEMBER_BG" IS '회원 테마색(1~8)';


-- 2. MEMBER_NO 컬럼 PK 제약조건 추가
ALTER TABLE "MEMBER" 
ADD CONSTRAINT "PK_MEMBER" 
PRIMARY KEY ("MEMBER_NO");

-- 3-1. MEMBER_NO 에 들어갈 SEQUENCE 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

-- 3-2. 최초 번호 생성
SELECT SEQ_MEMBER_NO.NEXTVAL FROM DUAL; 

-- 3-3. 현재 번호 확인
SELECT SEQ_MEMBER_NO.CURRVAL FROM DUAL; 

-- 3-4. 증감 변경 
ALTER SEQUENCE SEQ_MEMBER_NO INCREMENT BY 1;

SELECT * FROM "BOARD_TYPE";

DROP SEQUENCE SEQ_MEMBER_NO;
DROP TABLE "MEMBER" CASCADE CONSTRAINTS;

COMMIT;


-----------------------------------------------
-------------------CALENDER-----------------------
-----------------------------------------------

CREATE TABLE "CALENDER" (
	"CALENDER_ID" NUMBER NOT NULL, -- PK
	"START_DATE" DATE NOT NULL,
	"END_DATE"	DATE NOT NULL,
	"CALENDER_CONTENT" NVARCHAR2(100) NOT NULL, -- 특정 일자의 캘린더 내용
	"MEMBER_NO" NUMBER NOT NULL, -- FK
	CONSTRAINT "PK_CALENDER" PRIMARY KEY ("CALENDER_ID"),
	CONSTRAINT "FK_MEMBER_NO_TO_CALENDER" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")
	);

SELECT * FROM CALENDER;

CREATE SEQUENCE SEQ_CALENDER_ID;
ALTER SEQUENCE SEQ_CALENDER_ID INCREMENT BY 1;

INSERT INTO "CALENDER" VALUES(
	SEQ_CALENDER_ID.NEXTVAL,
	SYSDATE + 12,
	SYSDATE + 44,
	'테스트444',
	10
);

COMMIT;

-----------------------------------------------
-------------------TIMETABLE-----------------------
-----------------------------------------------

CREATE TABLE "TIMETABLE" (
	"TIMETABLE_ID"	NUMBER	NOT NULL,	
	"SEMESTER"			NVARCHAR2(10) NOT NULL, -- 학기 (형태 : 2026-1)
	"MEMBER_NO"			NUMBER NOT NULL,
	"DAY_CLASS_SUBJECT" VARCHAR2(150) DEFAULT '쉬는 날' NOT NULL -- DAY: 요일, CLASS: 교시, SUBJECT: 과목
);

/* 수정사항
 1) END_DATE 및 START_DATE 삭제
  - 사유 : 굳이 필요하지 않은 데이터인 듯하여 삭제하였습니다.
 
 2) SEMESTER(학기) 추가
  - 사유 : 1)과 관련하여, '2025년도 1학기', '2026년도 2학기' 등처럼 학기만 나타내주는 컬럼이 필요하여 추가
 
 3) DAY_OF_WEEK 을 NUMBER 타입으로 변경
  - 사유 : 일주일 단위기간을 숫자로 나타내어 오타로 인한 오류 방지 용이
  
 4) SUBJECT 를 NULL 허용으로 변경
  - 사유 : 반드시 7교시가 아니라 4교시, 5교시 등도 있을 수 있기 때문에 NULL 허용
*/

COMMENT ON COLUMN "TIMETABLE"."TIMETABLE_ID" IS '시간표번호(PK)';
COMMENT ON COLUMN "TIMETABLE"."DAY_OF_WEEK" IS '요일';
COMMENT ON COLUMN "TIMETABLE"."SEMESTER" IS '학기';
COMMENT ON COLUMN "TIMETABLE"."SUBJECT" IS '과목';
COMMENT ON COLUMN "TIMETABLE"."MEMBER_NO" IS '회원번호(FK)';

ALTER TABLE "TIMETABLE"
ADD CONSTRAINT "PK_TIMETABLE" 
PRIMARY KEY ("TIMETABLE_ID");

ALTER TABLE "TIMETABLE" ADD "DAY_CLASS_SUBJECT" VARCHAR2(150) DEFAULT '쉬는 날' NOT NULL;

ALTER TABLE "TIMETABLE" DROP COLUMN "DAY_OF_WEEK";

SELECT * FROM "TIMETABLE";

INSERT INTO "TIMETABLE" VALUES(
	SEQ_TIMETABLE_ID.NEXTVAL,
	'2025-2',
	10,
	'4-1-근현대사'
);

-- 


-- TIMETABLE_ID 에 들어갈 SEQUENCE 생성
CREATE SEQUENCE SEQ_TIMETABLE_ID NOCACHE;

-- 최초 번호 생성
SELECT SEQ_TIMETABLE_ID.NEXTVAL FROM DUAL; 

-- 현재 번호 확인
SELECT SEQ_TIMETABLE_ID.CURRVAL FROM DUAL; 

-- 증감 변경 
ALTER SEQUENCE SEQ_TIMETABLE_ID INCREMENT BY 1;

COMMIT;

DROP TABLE "TIMETABLE" CASCADE CONSTRAINTS;





-----------------------------------------------
-------------------BOARD_TYPE----------------------
-----------------------------------------------

CREATE TABLE "BOARD_TYPE" (
	"BOARD_TYPE_NO"		NUMBER			NOT NULL,
	"BOARD_TYPE_NAME"	NVARCHAR2(20)	NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_TYPE_NO" IS '게시판 종류코드반 번호(PK)';
COMMENT ON COLUMN "BOARD_TYPE"."BOARD_TYPE_NAME" IS '게시판 이름';

DROP SEQUENCE SEQ_BOARD_CODE;

CREATE SEQUENCE SEQ_BOARD_CODE
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 글자수 제한 초과로 인해 NVARCHAR2(20)으로 컬럼 타입 변경
ALTER TABLE "BOARD_TYPE" MODIFY "BOARD_TYPE_NAME" NVARCHAR2(20);

INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '자유 게시판');
INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '질문 게시판');
INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '급식표 게시판');
INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '입시정보 게시판');
INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '문제풀이 게시판');
INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '공지사항');
INSERT INTO "BOARD_TYPE" VALUES(SEQ_BOARD_CODE.NEXTVAL, '마이페이지 게시판'); -- 확인 후 수행할것

COMMIT;

SELECT * FROM BOARD_TYPE;

SELECT * FROM "COMMENT";

ALTER TABLE "BOARD_TYPE" 
ADD CONSTRAINT "PK_BOARD_TYPE" 
PRIMARY KEY ("BOARD_TYPE_NO");





-----------------------------------------------
-------------------BOARD-----------------------
-----------------------------------------------
--****************** "BOARD_NO" 이 아니라 "BOARD_ID" 임에 주의

CREATE TABLE "BOARD" (
	"BOARD_ID"	NUMBER	NOT NULL, --PK
	"BOARD_TITLE"	NVARCHAR2(20)	NOT NULL,
	"BOARD_CONTENT"	NVARCHAR2(2000)	NOT NULL, -- 게시글 내용 2000자
	"BOARD_VIEW_COUNT"	NUMBER	DEFAULT 0 NOT NULL,
	"BOARD_IS_DELETED"	CHAR(1)	DEFAULT 'N' NOT NULL,
	"BOARD_CREATE_DATE"	DATE	DEFAULT SYSDATE NOT NULL,
	"BOARD_UPDATE_DATE"	DATE	DEFAULT SYSDATE NOT NULL, -- 수정일자 DEFAULT 값 SYSDATE 로 추가, NOT NULL 로 변경
	"BOARD_TYPE_NO"	NUMBER	NOT NULL, -- FK
	"MEMBER_NO"	NUMBER	NOT NULL -- FK
);

-- PK 지정
ALTER TABLE "BOARD" 
ADD CONSTRAINT "PK_BOARD" 
PRIMARY KEY ("BOARD_ID");

-- 시퀀스 생성
CREATE SEQUENCE "SEQ_BOARD_ID"
START WITH 1
INCREMENT BY 1
NOCACHE;

-- FK 지정
ALTER TABLE "BOARD" 
ADD CONSTRAINT "FK_BOARD_TYPE TO BOARD" 
FOREIGN KEY ("BOARD_TYPE_NO")
REFERENCES "BOARD_TYPE" ("BOARD_TYPE_NO"); 

ALTER TABLE "BOARD" 
ADD CONSTRAINT "FK_MEMBER_NO TO BOARD" 
FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO"); 

SELECT * FROM "BOARD";
SELECT * FROM "BOARD_TYPE";
SELECT * FROM "COMMENT";

COMMIT;


BEGIN
	FOR I IN 1..100 LOOP
		
		INSERT INTO "BOARD"
		VALUES(SEQ_BOARD_ID.NEXTVAL,
					 SEQ_BOARD_ID.CURRVAL || '번째 게시글 제목 테스트',
					 SEQ_BOARD_ID.CURRVAL || '번째 게시글 내용 테스트',
					 DEFAULT, 
					 DEFAULT, 
					 DEFAULT, 
					 DEFAULT,
					 CEIL(DBMS_RANDOM.VALUE(0,6)), -- 0.0 이상 6.0 미만 난수발생시켜 BOARD_TYPE 랜덤 지정
					 10 -- 회원번호
		);

	END LOOP;
END;

---------게시판별 5개씩 조회수 탑5 게시글 조회, 댓글수, 게시판별 순위, 해당 글이 게시판에서 몇 번째 글인지 포함---------------------------
SELECT * FROM (
    SELECT 
        B.*,
        -- 작성일이 현재 시간으로부터 24시간(1일) 이내면 1, 아니면 2
        CASE 
            WHEN (SYSDATE - B.BOARD_CREATE_DATE) <= 1 THEN 1
            ELSE 2
        END AS IS_NEW,
        
        -- 댓글 수 조회
        (SELECT COUNT(*) 
         FROM "COMMENT" C
         WHERE C.BOARD_ID = B.BOARD_ID) AS COMMENT_COUNT,
         
         -- 메인화면에서 연결할 CP 값을 생성하기 위한 부분
         -- 특정 게시글이 특정 BOARD_TYPE 게시판에서 몇 번째 글인지 파악함
         ROW_NUMBER() OVER ( 
            PARTITION BY B.BOARD_TYPE_NO 
            ORDER BY B.BOARD_ID DESC
        ) AS MAIN_CP,
         
        -- 게시판별 순위 계산
        ROW_NUMBER() OVER ( 
            PARTITION BY B.BOARD_TYPE_NO 
            ORDER BY B.BOARD_VIEW_COUNT DESC, B.BOARD_ID DESC
        ) AS RANK 
    FROM "BOARD" B
    WHERE B.BOARD_IS_DELETED = 'N'
    AND B.BOARD_CREATE_DATE >= SYSDATE - 7
)
WHERE RANK <= 5
AND ROWNUM <= 30
ORDER BY BOARD_TYPE_NO, RANK;
-------------------------------------------------------------------------

-----------------------------------------------
-------------------COMMENT-----------------------
-----------------------------------------------

CREATE TABLE "COMMENT" (
	"COMMENT_NO"			NUMBER	NOT NULL, --PK
	"COMMENT_CONTENT" NVARCHAR2(1000)	NOT NULL, -- 댓글 내용 1000자
	"COMMENT_WRITE_DATE"	DATE	DEFAULT SYSDATE NOT NULL, -- DEFAULT SYSDATE 추가
	"COMMENT_DEL_FL"		CHAR(1)	DEFAULT 'N' NOT NULL,
	"BOARD_ID"	NUMBER	NOT NULL, -- FK
	"MEMBER_NO"	NUMBER	NOT NULL,	-- FK
	"PARENT_COMMENT_NO"	NUMBER	NOT NULL	-- FK
);

ALTER TABLE "COMMENT" RENAME COLUMN "BOARD_NO" TO "BOARD_ID";

-- PK 지정
ALTER TABLE "COMMENT" 
ADD CONSTRAINT "PK_COMMENT" 
PRIMARY KEY ("COMMENT_NO");

-- 시퀀스 생성
CREATE SEQUENCE "SEQ_COMMENT_NO"
START WITH 1
INCREMENT BY 1
NOCACHE;

-- FK 지정
ALTER TABLE "COMMENT" 
ADD CONSTRAINT "FK_BOARD_ID TO COMMENT" 
FOREIGN KEY ("BOARD_ID")
REFERENCES "BOARD" ("BOARD_ID"); 

ALTER TABLE "COMMENT"
ADD CONSTRAINT "FK_MEMBER_NO TO COMMENT"
FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");

ALTER TABLE "COMMENT"
ADD CONSTRAINT "FK_PARENT_COMMENT_NO TO COMMENT"
FOREIGN KEY ("COMMENT_NO")
REFERENCES "COMMENT" ("COMMENT_NO");

SELECT * FROM "COMMENT";




-----------------------------------------------
------------------BOARD_IMG-----------------------
-----------------------------------------------

CREATE TABLE "BOARD_IMG" (
	"IMG_NO"	NUMBER	NOT NULL,	-- '이미지 번호(PK)',
	"IMG_PATH"	VARCHAR(200)	NOT NULL,	-- '이미지 요청 경로',
	"IMG_ORIGINAL_NAME"	NVARCHAR2(50)	NOT NULL,	-- '이미지 원본명',
	"IMG_RENAME"	NVARCHAR2(50)	NOT NULL,
	"IMG_ORDER"	NUMBER	NULL,
	"BOARD_ID"	NUMBER	NOT NULL -- FK
);

-- PK 생성
ALTER TABLE "BOARD_IMG" 
ADD CONSTRAINT "PK_BOARD_IMG" 
PRIMARY KEY ("IMG_NO");

-- 시퀀스 생성
CREATE SEQUENCE "SEQ_IMG_NO"
START WITH 1
INCREMENT BY 1
NOCACHE;

-- FK 지정
ALTER TABLE "BOARD_IMG"
ADD CONSTRAINT "FK_BOARD_ID TO BOARD_IMG"
FOREIGN KEY ("BOARD_ID")
REFERENCES "BOARD" ("BOARD_ID");






-----------------------------------------------
------------------BOARD_LIKE-------------------
-----------------------------------------------

CREATE TABLE "BOARD_LIKE" (
	"MEMBER_NO"	NUMBER	NOT NULL,	-- '회원번호(PFK)'
	"BOARD_ID"	NUMBER	NOT NULL	-- '게시글번호(PK)'
);

-- PK 지정

ALTER TABLE "BOARD_LIKE" 
ADD CONSTRAINT "PK_BOARD_LIKE" 
PRIMARY KEY ("MEMBER_NO", "BOARD_ID");

ALTER TABLE "BOARD_LIKE"
ADD CONSTRAINT "FK_MEMBER_NO TO BOARD_LIKE"
FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");

SELECT * FROM "BOARD_LIKE";




-----------------------------------------------
------------------UPLOAD_FILE-------------------
-----------------------------------------------

CREATE TABLE "UPLOAD_FILE" (
	"UPLOADFILE_NO"	NUMBER	NOT NULL,	-- '파일 번호'
	"UPLOADFILE_ORIGIN"	VARCHAR2(150)	NOT NULL,	--'원본 파일명'
	"UPLOADFILE_PATH"	VARCHAR2(1000)	NOT NULL,	--'파일 경로'
	"UPLOADFILE_STRG"	VARCHAR2(150)	NOT NULL,	-- '저장 파일명'
	"UPLOADFILE_SIZE"	NUMBER	NOT NULL,	-- '파일 크기'
	"UPLOADFILE_DATE"	DATE	DEFAULT SYSDATE NOT NULL,	
	"BOARD_ID"	NUMBER	NOT NULL	-- '게시글번호(FK)'
);

-- PK 생성
ALTER TABLE "UPLOAD_FILE" 
ADD CONSTRAINT "PK_UPLOAD_FILE" 
PRIMARY KEY ("UPLOADFILE_NO");

-- 시퀀스 생성
CREATE SEQUENCE "SEQ_UPLOADFILE_NO"
START WITH 1
INCREMENT BY 1
NOCACHE;

-- FK 지정
ALTER TABLE "UPLOAD_FILE"
ADD CONSTRAINT "FK_BOARD_ID TO UPLOAD_FILE"
FOREIGN KEY ("BOARD_ID")
REFERENCES "BOARD" ("BOARD_ID");

COMMIT;




-----------------------------------------------
------------------WRONG_NOTE-------------------
-----------------------------------------------

CREATE TABLE "WRONG_NOTE" (
	"WRONG_NOTE_NO"				NUMBER	NOT NULL,	-- 오답노트 번호 PK
	"WRONG_NOTE_TITLE"		VARCHAR2(200)	NOT NULL,	-- '오답노트 제목',
	"WRONG_NOTE_CONTENT"	VARCHAR2(4000)	NOT NULL,	-- '오답노트 틀린문제',
	"WRONG_NOTE_MYANSWER" VARCHAR2(4000)  NOT NULL, -- 내 오답
	"WRONG_NOTE_EXPLAIN"	VARCHAR2(4000) 	NOT NULL, -- 오답노트 풀이
	"WRONG_NOTE_TYPE"			NUMBER NOT NULL, -- 오답노트 종류(1: 객관식, 2: 주관식, 3: 논술형)
	"WRONG_NOTE_DATE"			DATE DEFAULT SYSDATE NOT NULL,	 -- '오답노트 작성일',
	"MEMBER_NO"						NUMBER	NOT NULL,	-- '회원번호(FK)'
	"WRONG_NOTE_UNDERSTOOD" 	NUMBER DEFAULT 1 NOT NULL --  여부 (1: 틀림, 2: 이해함)
);

ALTER TABLE "WRONG_NOTE"
ADD CONSTRAINT "PK_WRONG_NOTE"
PRIMARY KEY ("WRONG_NOTE_NO");

ALTER TABLE "WRONG_NOTE"
ADD "WRONG_NOTE_UNDERSTOOD" NUMBER DEFAULT 1 NOT NULL;

CREATE SEQUENCE "SEQ_WRONG_NOTE_NO" 
START WITH 5
INCREMENT BY 1
NOCACHE;

ALTER TABLE "WRONG_NOTE"
ADD CONSTRAINT "FK_MEMBER_NO TO WRONG_NOTE"
FOREIGN KEY ("MEMBER_NO")
REFERENCES "MEMBER" ("MEMBER_NO");

SELECT * FROM "WRONG_NOTE";

SELECT * FROM "WRONG_NOTE"
ORDER BY "WRONG_NOTE_NO" DESC
FETCH FIRST 1 ROWS ONLY;

SELECT * FROM "WRONG_NOTE"
ORDER BY "WRONG_NOTE_NO" ASC;

-- DROP SEQUENCE "SEQ_WRONG_NOTE";
-- DROP TABLE "WRONG_NOTE";

INSERT INTO "WRONG_NOTE" VALUES(
	SEQ_WRONG_NOTE_NO.NEXTVAL,
	'2025 6월 모의고사 수리영역 8번 문제',
	'2x + 8 = 16일 때 x의 값은?',
	'4',
	'맞췄다!',
	1,
	DEFAULT,
	10,
	2
);

DELETE FROM "WRONG_NOTE"
WHERE "WRONG_NOTE_NO" = 3;

COMMIT;

-- *** 오답노트 풀이, 오답노트 종류 컬럼 추가

-- !!!!!! 아래부터 주석처리함.
-- !!!!!! 필요한 거 잘라내서 추가해주세요

/* 



CREATE TABLE `TODO` (
	`TODO_NO`	NUMBER	NOT NULL	COMMENT '할일 번호(PK)',
	`TODO_TITLE`	VARCHAR(200)	NOT NULL	COMMENT '할일 제목',
	`TODO_CONTENT`	VARCHAR2(4000)	NOT NULL	COMMENT '할일 내용',
	`TODO_CHECK`	CHAR(1)	NULL	DEFAULT N	COMMENT '할일 체크',
	`TODO_DATE`	DATE	NOT NULL	COMMENT '할일 날짜',
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(FK)'
);


CREATE TABLE `DIARY` (
	`DIARY_NO`	NUMBER	NOT NULL	COMMENT '일기장 번호(PK)',
	`DIARY_DATE`	DATE	NOT NULL	COMMENT '일기장 날짜',
	`DIARY_TITLE`	NVARCHAR2(50)	NOT NULL	COMMENT '일기장 제목',
	`DIARY_CONTENT`	NVARCHAR2(2000)	NOT NULL	COMMENT '일기장 내용',
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(FK)'
);

CREATE TABLE `INQUIRY` (
	`INQUIRY_NO`	NUMBER	NOT NULL	COMMENT '문의 번호',
	`INQUIRY_TITLE`	NVARCHAR2(50)	NOT NULL	COMMENT '문의사항 분류',
	`INQUIRY_CONTENT`	NVARCHAR2(1000)	NOT NULL	COMMENT '세부문의사항',
	`INQUIRY_COMPLETE`	CHAR(1)	NOT NULL	DEFAULT N	COMMENT '조치완료여부(N/Y)',
	`INQUIRY_DATE`	DATE	NOT NULL	COMMENT '문의한 날짜',
	`INQUIRY_COMPLETE_DATE`	DATE	NOT NULL	COMMENT '답변한 날짜',
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(PK)'
);


CREATE TABLE `CHAT_MESSAGE` (
	`MSG_NO`	NUMBER	NOT NULL	COMMENT '메시지 고유 번호(PK)',
	`MESSAGE`	VARCHAR2(4000)	NOT NULL	COMMENT '메시지 내용',
	`READ_YN`	CHAR(1)	NOT NULL	COMMENT '읽음 여부("Y" 또는 "N")',
	`SEND_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '보낸 시간(기본값: 현재시간)',
	`ROOM_NO2`	NUMBER	NOT NULL	COMMENT '채팅방 번호(PK)',
	`SENDER_NO`	NUMBER	NOT NULL	COMMENT '메시지보낸회원번호(PK)'
);



CREATE TABLE `ATTENDANCE` (
	`ATTENDANCE_DATE`	DATE	NOT NULL	COMMENT '출석시간(PK)',
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(PFK)',
	`ATTENDANCE_NO`	NUMBER	NOT NULL	COMMENT '출석고유번호(UNIQUE)'
);

CREATE TABLE `AUTH_KEY_EMAIL` (
	`EMAIL_KEY_NO`	NUMBER	NOT NULL	COMMENT '이메일 인증 키 번호(PK)',
	`EMAIL`	NVARCHAR2(50)	NOT NULL	COMMENT '이메일 주소',
	`AUTH_KEY`	CHAR(6)	NOT NULL	COMMENT '이메일 인증 번호',
	`AUTH_CREATE_TIME`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '이메일 인증번호 생성 시간'
);

CREATE TABLE `D_DAY` (
	`D_DAY_NO`	NUMBER	NOT NULL	COMMENT 'D_DAY PK',
	`D_DAY_TITLE`	NVARCHAR2(20)	NULL,
	`D_DAY_MENT`	NVARCHAR2(100)	NULL,
	`D_DAY`	DATE	NULL,
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(FK)'
);

CREATE TABLE `POINT_LOG` (
	`POINT_LOG_ID`	NUMBER	NOT NULL	COMMENT '포인트번호(PK)',
	`POINT`	NUMBER	NOT NULL,
	`POINT_REASON`	NVARCHAR(255)	NOT NULL,
	`POINT_CREATE_AT`	DATE	NOT NULL,
	`MEMBER_NO`	NUMBER	NOT NULL	COMMENT '회원번호(PK)',
	`ATTENDANCE_NO`	NUMBER	NOT NULL	COMMENT '출석고유번호(UNIQUE)'
);



CREATE TABLE `CHAT_ROOM` (
	`ROOM_NO`	NUMBER	NOT NULL	COMMENT '채팅방 번호(PK)',
	`CREATE_DATE`	DATE	NOT NULL	DEFAULT SYSDATE	COMMENT '생성일',
	`PARTICIPANT`	NUMBER	NOT NULL	COMMENT '참여자(FK)',
	`OPEN_MEMBER`	NUMBER	NOT NULL	COMMENT '개설자(FK)'
);





ALTER TABLE `TODO` ADD CONSTRAINT `PK_TODO` PRIMARY KEY (
	`TODO_NO`
);

ALTER TABLE `DIARY` ADD CONSTRAINT `PK_DIARY` PRIMARY KEY (
	`DIARY_NO`
);

ALTER TABLE `INQUIRY` ADD CONSTRAINT `PK_INQUIRY` PRIMARY KEY (
	`INQUIRY_NO`
);

ALTER TABLE `CHAT_MESSAGE` ADD CONSTRAINT `PK_CHAT_MESSAGE` PRIMARY KEY (
	`MSG_NO`
);

ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `PK_ATTENDANCE` PRIMARY KEY (
	`ATTENDANCE_DATE`,
	`MEMBER_NO`
);

ALTER TABLE `AUTH_KEY_EMAIL` ADD CONSTRAINT `PK_AUTH_KEY_EMAIL` PRIMARY KEY (
	`EMAIL_KEY_NO`
);

ALTER TABLE `D_DAY` ADD CONSTRAINT `PK_D_DAY` PRIMARY KEY (
	`D_DAY_NO`
);

ALTER TABLE `POINT_LOG` ADD CONSTRAINT `PK_POINT_LOG` PRIMARY KEY (
	`POINT_LOG_ID`
);


ALTER TABLE `CHAT_ROOM` ADD CONSTRAINT `PK_CHAT_ROOM` PRIMARY KEY (
	`ROOM_NO`
);


ALTER TABLE `ATTENDANCE` ADD CONSTRAINT `FK_MEMBER_TO_ATTENDANCE_1` FOREIGN KEY (
	`MEMBER_NO`
)

*/