-- =========================
-- GOODSUGAR CLEAN (DEV)
-- =========================

-- TRIGGER (있을 수도 있으니 삭제)
DROP TRIGGER TRG_GLUCOSE_RECORD_BI;
DROP TRIGGER TRG_EMAIL_VERIFY_BI;
DROP TRIGGER TRG_MEMBER_BI;

-- TABLE (자식 → 부모)
DROP TABLE EMAIL_VERIFY CASCADE CONSTRAINTS PURGE;
DROP TABLE GLUCOSE_RECORD CASCADE CONSTRAINTS PURGE;
DROP TABLE MEMBER CASCADE CONSTRAINTS PURGE;

-- SEQUENCE
DROP SEQUENCE SEQ_EMAIL_VERIFY;
DROP SEQUENCE SEQ_GLUCOSE_RECORD;
DROP SEQUENCE SEQ_MEMBER;




CREATE SEQUENCE SEQ_MEMBER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EMAIL_VERIFY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_GLUCOSE_RECORD START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


CREATE TABLE MEMBER (
  MEMBER_ID       NUMBER(20) PRIMARY KEY,

  EMAIL           VARCHAR2(100) NOT NULL,
  NICKNAME        VARCHAR2(50)  NOT NULL,

  LOGIN_TYPE      VARCHAR2(20) DEFAULT 'LOCAL' NOT NULL, -- LOCAL / OAUTH
  PASSWORD_HASH   VARCHAR2(200),

  OAUTH_PROVIDER  VARCHAR2(20),
  OAUTH_UID       VARCHAR2(100),

  NAME            VARCHAR2(50),
  GENDER          VARCHAR2(10),
  PROFILE_IMG     VARCHAR2(400),
  MEMBER_BIRTH    DATE,

  CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATE_AT       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  LAST_LOGIN_AT   TIMESTAMP,
  WITHDRAW_AT     TIMESTAMP,

  STATUS          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL, -- ACTIVE / BLOCKED / WITHDRAW
  ROLE            VARCHAR2(20) DEFAULT 'USER' NOT NULL     -- USER / ADMIN
);

SELECT * FROM MEMBER;

ALTER TABLE MEMBER ADD CONSTRAINT UK_MEMBER_EMAIL UNIQUE (EMAIL);
ALTER TABLE MEMBER ADD CONSTRAINT UK_MEMBER_NICKNAME UNIQUE (NICKNAME);
ALTER TABLE MEMBER ADD CONSTRAINT UK_MEMBER_OAUTH UNIQUE (OAUTH_PROVIDER, OAUTH_UID);

ALTER TABLE MEMBER ADD CONSTRAINT CK_MEMBER_LOGIN_TYPE
CHECK (LOGIN_TYPE IN ('LOCAL','OAUTH'));

ALTER TABLE MEMBER ADD CONSTRAINT CK_MEMBER_STATUS
CHECK (STATUS IN ('ACTIVE','BLOCKED','WITHDRAW'));

ALTER TABLE MEMBER ADD CONSTRAINT CK_MEMBER_ROLE
CHECK (ROLE IN ('USER','ADMIN'));

ALTER TABLE MEMBER ADD CONSTRAINT CK_MEMBER_OAUTH_PROVIDER
CHECK (OAUTH_PROVIDER IS NULL OR OAUTH_PROVIDER IN ('KAKAO','NAVER','GOOGLE'));

CREATE INDEX IDX_MEMBER_STATUS ON MEMBER(STATUS);



CREATE TABLE EMAIL_VERIFY (
  VERIFY_ID    NUMBER(20) PRIMARY KEY,
  MEMBER_ID    NUMBER(20),
  EMAIL        VARCHAR2(100) NOT NULL,
  VERIFY_CODE  VARCHAR2(20)  NOT NULL,
  EXPIRED_AT   TIMESTAMP     NOT NULL,
  VERIFIED_AT  TIMESTAMP
);

ALTER TABLE EMAIL_VERIFY
ADD CONSTRAINT FK_EMAIL_VERIFY_MEMBER
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID);

CREATE INDEX IDX_EMAIL_VERIFY_EMAIL ON EMAIL_VERIFY(EMAIL);
CREATE INDEX IDX_EMAIL_VERIFY_MEMBER ON EMAIL_VERIFY(MEMBER_ID);
CREATE INDEX IDX_EMAIL_VERIFY_EMAIL_CODE ON EMAIL_VERIFY(EMAIL, VERIFY_CODE);
CREATE INDEX IDX_EMAIL_VERIFY_EXPIRED ON EMAIL_VERIFY(EXPIRED_AT);



CREATE TABLE GLUCOSE_RECORD (
  RECORD_ID          NUMBER(20) PRIMARY KEY,
  MEMBER_ID          NUMBER(20) NOT NULL,

  GLUCOSE_VALUE      NUMBER(5),

  DRINK_YN           CHAR(1) DEFAULT 'N' NOT NULL,
  EXERCISE_YN        CHAR(1) DEFAULT 'N' NOT NULL,
  EXERCISE_CONTENTS  VARCHAR2(100),

  MEASURE_DATE       DATE NOT NULL,
  MEASURE_TIME       TIMESTAMP,

  MEASURE_TYPE       VARCHAR2(20) NOT NULL,

  MEDICATION_YN      CHAR(1) DEFAULT 'N' NOT NULL,
  MEDICATION_INFO    VARCHAR2(100),

  INJECTION_YN       CHAR(1) DEFAULT 'N' NOT NULL,
  INJECTION_INFO     VARCHAR2(100),

  DIET               VARCHAR2(100),
  LOG_CONTENT        VARCHAR2(200),

  GLUCOSE_TYPE       VARCHAR2(20) NOT NULL, -- ✅ 자유입력 + 필수

  CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

ALTER TABLE GLUCOSE_RECORD
ADD CONSTRAINT FK_GLUCOSE_MEMBER
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID);

ALTER TABLE GLUCOSE_RECORD ADD CONSTRAINT CK_GR_DRINK_YN
CHECK (DRINK_YN IN ('Y','N'));

ALTER TABLE GLUCOSE_RECORD ADD CONSTRAINT CK_GR_EXERCISE_YN
CHECK (EXERCISE_YN IN ('Y','N'));

ALTER TABLE GLUCOSE_RECORD ADD CONSTRAINT CK_GR_MEDICATION_YN
CHECK (MEDICATION_YN IN ('Y','N'));

ALTER TABLE GLUCOSE_RECORD ADD CONSTRAINT CK_GR_INJECTION_YN
CHECK (INJECTION_YN IN ('Y','N'));

ALTER TABLE GLUCOSE_RECORD ADD CONSTRAINT CK_GR_MEASURE_TYPE
CHECK (MEASURE_TYPE IN ('FASTING','BEFORE_MEAL','AFTER_1H','AFTER_2H','UNKNOWN'));

CREATE INDEX IDX_GR_MEMBER_DATE ON GLUCOSE_RECORD(MEMBER_ID, MEASURE_DATE);
CREATE INDEX IDX_GR_MEMBER_TYPE ON GLUCOSE_RECORD(MEMBER_ID, MEASURE_TYPE);

CREATE TABLE BOARD (
    BOARD_ID            NUMBER          PRIMARY KEY,
    BOARD_TITLE         NVARCHAR2(20)   NOT NULL,
    BOARD_CONTENT       NVARCHAR2(2000) NOT NULL, 
    BOARD_VIEW_COUNT    NUMBER          DEFAULT 0 NOT NULL,
    BOARD_DELETED_FL    CHAR(1)         DEFAULT 'N' NOT NULL,
    BOARD_CREATE        DATE            DEFAULT SYSDATE NOT NULL,
    BOARD_UPDATE        DATE            DEFAULT SYSDATE NOT NULL, 
    IS_ANONYMOUS_YN     CHAR(1)         DEFAULT 'N' CHECK (IS_ANONYMOUS_YN IN ('Y', 'N')),
    ANONYMOUS_NAME      NVARCHAR2(40)   NULL,
    BOARD_TYPE_ID       NUMBER          NOT NULL,
    MEMBER_ID           NUMBER          NOT NULL 
);



