# Fileë¡ ìì±í´ì ì´ë¦ì config.properties ë¼ê³  ìì±í­ì¬ ìì±
# *** .gitignore íì¼ì config.properties ìì±íì¸ ****

#ì¤ë¼í´ DB ì°ê²° ì ë³´
spring.datasource.hikari.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.hikari.jdbc-url=jdbc:oracle:thin:@1.223.77.182:12345:XE
spring.datasource.hikari.username=bakeji
spring.datasource.hikari.password=12121
# HikariCP Connection Pool Properties
#ì»¤ë¥ì(ì°ê²°)ì ì¬ì©í  ì ìì ëê¹ì§ ëê¸°íë ìµë ìê°(ms)ì ì§ì 
spring.datasource.hikari.connection-timeout=30000

#íì ìµë ì°ê²° ì ì¤ì 
spring.datasource.hikari.maximum-pool-size=5

#ì°ê²°ì´ íìì ì í´ ìíë¡ ìì ì ìë ìµë ìê°(ms)ì ì§ì 
spring.datasource.hikari.idle-timeout=600000

#ì°ê²° íì ì´ë¦ì ì§ì 
spring.datasource.hikari.pool-name=MyHikariCP

#ìë ì»¤ë° ëê¸°
spring.datasource.hikari.auto-commit=false


spring.mail.username=chulkuji12@gmail.com
spring.mail.password=quidqouqttmovcqr


# (ì°¸ê³ )
# 1MB = 1024KB
# 1KB = 1024B

# íì¼ì ëì¤í¬ì ì¸ ëê¹ì§ì ìê³ ê°
# ê¸°ë³¸ ê° : 0B
# 50MBë¡ ë³ê²½ == 52,428,800 B
# -> ìë¡ëëë íì¼ì í¬ê¸° 50MB ê¹ì§ë ë©ëª¨ë¦¬ì ììë¡ ì ì¥íë¤ê°
# ì´ê³¼ ì ëì¤í¬(HDD, SSD)ì ì ì¥
spring.servlet.multipart.file-size-threshold=52428800

# ìê³ ê° ì´ê³¼ ì íì¼ì ìì ì ì¥ ê²½ë¡
# ë§ì§ë§ì / ê¼­ ìì±í´ì¤ì¼ í¨
spring.servlet.multipart.location=C:/uploadFiles/temp/

# HTTP ìì²­ë¹ ìµë í¬ê¸°
# ê¸°ë³¸ ê° : 10MB
# 50MB ë¡ ë³ê²½
spring.servlet.multipart.max-request-size=52428800

# ê°ë³ íì¼ë¹ ìµë í¬ê¸°
# ê¸°ë³¸ ê° : 1MB
# 10MB ë¡ ë³ê²½
spring.servlet.multipart.max-file-size=10485760

#----------------------------------------

# íë¡í ì´ë¯¸ì§ ìì²­ ì£¼ì (FileConfig)
my.profile.resource-handler=/myPage/profile/**

# íë¡í ì´ë¯¸ì§ ìì²­ ì ì°ê²°ë  ìë² í´ë ê²½ë¡ (FileConfig)
my.profile.resource-location=file:///C:/uploadFiles/profile

# ìë¹ì¤ìì íë¡í ì´ë¯¸ì§ ìì²­ ì£¼ìë¥¼ ì¡°í©í  ë ì¬ì©íë ê²½ë¡(MyPageServiceImpl)
my.profile.web-path=/myPage/profile/

# ìë¹ì¤ìì íì¼ ì ì¥(transferTo()) ì ì¬ì©í  í´ë ê²½ë¡(MyPageServiceImpl)
my.profile.folder-path=C:/uploadFiles/profile/

#----------------------------------------------

#ê²ìê¸ ì´ë¯¸ì§ ìì²­ ì£¼ì : í´ë¼ì´ì¸í¸ê° ì´ë¤ ë¯¸ë¯¸ì§ë¥¼ ë³´ê³ ì¶ì´í  ë ìì²­ ë³´ë¼ë 
#(FileConfig)
my.board.resource-handler=/images/board/**

#ê²ìê¸ ì´ë¯¸ì§ ìì²­ ì ì°ê²° ë  í´ë ê²½ë¡
my.board.resource-location=file:///c:/uploadFiles/board/

#ê²ìê¸ ì´ë¯¸ì§ ìì²­ ì£¼ì (DB ì ì¥ì©)
my.board.web-path=/images/board/

#rptlrmf dlalwlfmf tjqjdp wjwkdgkf EO tkdydgkf rudfh
my.board.folder-path=c:/uploadfiles/board/


#log íì¼ì´ ì ì¥ë  ê²½ë¡
log.config.path=c:/log/

# logíì¼ì ì´ë¦
log.config.fileName=boardProject-log
